// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconIcRoundDiscord: typeof import('~icons/ic/round-discord')['default']
    IconLaDiscord: typeof import('~icons/la/discord')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideTwitter: typeof import('~icons/lucide/twitter')['default']
    IconLucideYoutube: typeof import('~icons/lucide/youtube')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
