// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconLaDiscord: typeof import('~icons/la/discord')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideLanguages: typeof import('~icons/lucide/languages')['default']
    IconLucideLinkedin: typeof import('~icons/lucide/linkedin')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconLucideTwitter: typeof import('~icons/lucide/twitter')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
