// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconEmojionePenguin: typeof import('~icons/emojione/penguin')['default']
    IconIcBaselineSchool: typeof import('~icons/ic/baseline-school')['default']
    IconLaDiscord: typeof import('~icons/la/discord')['default']
    IconLogosC: typeof import('~icons/logos/c')['default']
    IconLogosDockerIcon: typeof import('~icons/logos/docker-icon')['default']
    IconLogosGitIcon: typeof import('~icons/logos/git-icon')['default']
    IconLogosGo: typeof import('~icons/logos/go')['default']
    IconLogosGopher: typeof import('~icons/logos/gopher')['default']
    IconLogosHaskellIcon: typeof import('~icons/logos/haskell-icon')['default']
    IconLogosJava: typeof import('~icons/logos/java')['default']
    IconLogosKotlin: typeof import('~icons/logos/kotlin')['default']
    IconLogosKotlinIcon: typeof import('~icons/logos/kotlin-icon')['default']
    IconLogosNuxtIcon: typeof import('~icons/logos/nuxt-icon')['default']
    IconLogosPostgresql: typeof import('~icons/logos/postgresql')['default']
    IconLogosPython: typeof import('~icons/logos/python')['default']
    IconLogosRabbitmqIcon: typeof import('~icons/logos/rabbitmq-icon')['default']
    IconLogosRust: typeof import('~icons/logos/rust')['default']
    IconLogosSuse: typeof import('~icons/logos/suse')['default']
    IconLogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    IconLogosVim: typeof import('~icons/logos/vim')['default']
    IconLogosVoid: typeof import('~icons/logos/void')['default']
    IconLucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideGithub: typeof import('~icons/lucide/github')['default']
    IconLucideHeart: typeof import('~icons/lucide/heart')['default']
    IconLucideLinkedin: typeof import('~icons/lucide/linkedin')['default']
    IconLucideLove: typeof import('~icons/lucide/love')['default']
    IconLucideMail: typeof import('~icons/lucide/mail')['default']
    IconLucideStar: typeof import('~icons/lucide/star')['default']
    IconLucideTwitter: typeof import('~icons/lucide/twitter')['default']
    IconSimpleIconsOpensuse: typeof import('~icons/simple-icons/opensuse')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
